env:
  global:
    - NODE_ENV=test

language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
install:
- npm install

script:
  - npm run test:CI

after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coveralls