  
language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
install:
- npm install

script:
  - npm run test:unit -- --coverage  # Include coverage when running tests
  
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: develop