export const CREATE_ACCOMMODATION_REQUEST = 'CREATE_ACCOMMODATION_REQUEST';
export const CREATE_ACCOMMODATION_SUCCESS = 'CREATE_ACCOMMODATION_SUCCESS';
export const CREATE_ACCOMMODATION_FAILURE = 'CREATE_ACCOMMODATION_FAILURE';
export const CREATE_ACCOMMODATION_END = 'CREATE_ACCOMMODATION_END';

export const FETCH_ACCOMMODATION_START = 'FETCH_ACCOMMODATION_START';
export const FETCH_ACCOMMODATION_END = 'FETCH_ACCOMMODATION_END';
export const FETCH_ACCOMMODATION_SUCCESS = 'FETCH_ACCOMMODATION_SUCCESS';
export const FETCH_ACCOMMODATION_FAILURE = 'FETCH_ACCOMMODATION_FAILURE';

export const FETCH_SPECIFIC_ACCOMMODATION_START = 'FETCH_SPECIFIC_ACCOMMODATION_START';
export const FETCH_SPECIFIC_ACCOMMODATION_END = 'FETCH_SPECIFIC_ACCOMMODATION_END';
export const FETCH_SPECIFIC_ACCOMMODATION_SUCCESS = 'FETCH_SPECIFIC_ACCOMMODATION_SUCCESS';
export const FETCH_SPECIFIC_ACCOMMODATION_FAILURE = 'FETCH_SPECIFIC_ACCOMMODATION_FAILURE';

export const DELETE_ACCOMMODATION_START = 'DELETE_ACCOMMODATION_START';
export const DELETE_ACCOMMODATION_END = 'DELETE_ACCOMMODATION_END';
export const DELETE_ACCOMMODATION_SUCCESS = 'DELETE_ACCOMMODATION_SUCCESS';
export const DELETE_ACCOMMODATION_FAILURE = 'DELETE_ACCOMMODATION_FAILURE';

export const EDIT_ACCOMMODATION_START = 'EDIT_ACCOMMODATION_START';
export const EDIT_ACCOMMODATION_END = 'EDIT_ACCOMMODATION_END';
export const EDIT_ACCOMMODATION_SUCCESS = 'EDIT_ACCOMMODATION_SUCCESS';
export const EDIT_ACCOMMODATION_FAILURE = 'EDIT_ACCOMMODATION_FAILURE';
