export const FETCH_ACCOMMODATION_START = 'FETCH_ACCOMMODATION_START';
export const FETCH_ACCOMMODATION_END = 'FETCH_ACCOMMODATION_END';
export const FETCH_ACCOMMODATION_SUCCESS = 'FETCH_ACCOMMODATION_SUCCESS';
export const FETCH_ACCOMMODATION_FAILURE = 'FETCH_ACCOMMODATION_FAILURE';
