export const FETCH_APPROVAL_START = 'FETCH_APPROVAL_START';
export const FETCH_APPROVAL_END = 'FETCH_APPROVAL_END';
export const FETCH_APPROVAL_SUCCESS = 'FETCH_APPROVAL_SUCCESS';
export const FETCH_APPROVAL_FAILURE = 'FETCH_APPROVAL_FAILURE';
