export const FETCH_APPROVALS_START = 'FETCH_APPROVALS_START';
export const FETCH_APPROVALS_END = 'FETCH_APPROVALS_END';
export const FETCH_APPROVALS_SUCCESS = 'FETCH_APPROVALS_SUCCESS';
export const FETCH_APPROVALS_FAILURE = 'FETCH_APPROVALS_FAILURE';
