export const APPROVE_APPROVAL_START = 'APPROVE_APPROVAL_START';
export const APPROVE_APPROVAL_END = 'APPROVE_APPROVAL_END';
export const APPROVE_APPROVAL_SUCCESS = 'APPROVE_APPROVAL_SUCCESS';
export const APPROVE_APPROVAL_FAILURE = 'APPROVE_APPROVAL_FAILURE';

export const REJECT_APPROVAL_START = 'REJECT_APPROVAL_START';
export const REJECT_APPROVAL_END = 'REJECT_APPROVAL_END';
export const REJECT_APPROVAL_SUCCESS = 'REJECT_APPROVAL_SUCCESS';
export const REJECT_APPROVAL_FAILURE = 'REJECT_APPROVAL_FAILURE';
