export const GET_COMMENTS_START = 'GET_COMMENTS_START';
export const GET_COMMENTS_END = 'GET_COMMENTS_END';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const ADD_COMMENTS_START = 'ADD_COMMENTS_START';
export const ADD_COMMENTS_END = 'ADD_COMMENTS_END';
export const ADD_COMMENTS_SUCCESS = 'ADD_COMMENTS_SUCCESS';
export const ADD_COMMENTS_FAILURE = 'ADD_COMMENTS_FAILURE';

export const DELETE_COMMENTS_START = 'ADD_COMMENTS_START';
export const DELETE_COMMENTS_END = 'ADD_COMMENTS_END';
export const DELETE_COMMENTS_SUCCESS = 'ADD_COMMENTS_SUCCESS';
export const DELETE_COMMENTS_FAILURE = 'ADD_COMMENTS_FAILURE';
