export const FETCH_REMEMBERME_DATA_START = 'FETCH_REMEMBERME_DATA_START';
export const FETCH_REMEMBERME_DATA_END = 'FETCH_REMEMBERME_DATA_END';
export const FETCH_REMEMBERME_DATA_SUCCESS = 'FETCH_REMEMBERME_DATA_SUCCESS';
export const FETCH_REMEMBERME_DATA_FAILURE = 'FETCH_REMEMBERME_DATA_FAILURE';

export const MAKE_REMEMBERME_START = 'MAKE_REMEMBERME_START';
export const MAKE_REMEMBERME_END = 'MAKE_REMEMBERME_END';
export const MAKE_REMEMBERME_SUCCESS = 'MAKE_REMEMBERME_SUCCESS';
export const MAKE_REMEMBERME_FAILURE = 'MAKE_REMEMBERME_FAILURE';
