export const GET_ALL_ROOMS = 'GET_ALL_ROOMS';
export const GET_ALL_ROOMS_FAIL = 'GET_ALL_ROOMS_FAIL';

export const BOOK_ROOM_SUCCESS = 'BOOK_ROOM_SUCCESS';
export const BOOK_ROOM_FAIL = 'BOOK_ROOM_FAIL';
export const BOOKED_ROOM_FAIL = 'BOOKED_ROOM_FAIL';

export const RESET_PROPS_TONULL = 'RESET_PROPS_TONULL';
