export const FETCH_REQUEST_START = 'FETCH_REQUEST_START';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';
export const FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE';

export const CREATE_TRIP_START = 'CREATE_TRIP_START';
export const CREATE_TRIP_END = 'CREATE_TRIP_END';
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';
export const CREATE_TRIP_FAILURE = 'CREATE_TRIP_FAILURE';

export const EDIT_TRIP_START = 'EDIT_TRIP_START';
export const EDIT_TRIP_END = 'EDIT_TRIP_END';
export const EDIT_TRIP_SUCCESS = 'EDIT_TRIP_SUCCESS';
export const EDIT_TRIP_FAILURE = 'EDIT_TRIP_FAILURE';
export const FETCH_ONEREQUEST_FAIL = 'FETCH_ONEREQUEST_FAIL';
export const FETCH_ONEREQUEST_UNAPPROVED = 'FETCH_ONEREQUEST_UNAPPROVED';

export const GET_DESTINATION_START = 'GET_DESTINATION_START ';
export const GET_DESTINATION_END = 'GET_DESTINATION_END';
export const GET_DESTINATION_SUCCESS = 'GET_DESTINATION_SUCCESS';
export const GET_DESTINATION_FAIL = 'GET_DESTINATION_FAIL';

export const GET_STATS_START = 'GET_STATS_START ';
export const GET_STATS_END = 'GET_STATS_END';
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';
export const GET_STATS_FAIL = 'GET_STATS_FAIL';
export const FETCH_REQUEST_END = 'FETCH_REQUEST_END';
