export const CLEAR_USER_STORE = 'CLEAR_USER_STORE';

export const OAUTH_SUCCESS = 'OAUTH_SUCCESS';
export const OAUTH_FAILURE = 'OAUTH_FAILURE';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_END = 'LOGOUT_END';

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_END = 'FORGOT_PASSWORD_END';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_END = 'RESET_PASSWORD_END';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const SIGNUP_VALIDATION_ERROR = 'SIGNUP_VALIDATION_ERROR';
export const ADMIN_EDIT_ROLE_START = 'ADMIN_EDIT_ROLE_START';
export const ADMIN_EDIT_ROLE_END = 'ADMIN_EDIT_ROLE_END';
export const ADMIN_EDIT_ROLE_SUCCESS = 'ADMIN_EDIT_ROLE_SUCCESS';
export const ADMIN_EDIT_ROLE_FAIL = 'ADMIN_EDIT_ROLE_FAIL';

export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_END = 'GET_USERS_END';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
