export const GET_USER_PROFILE__SUCCESS = 'GET_USER_PROFILE__SUCCESS';
export const GET_USER_TRAVEL_SUCCESS = 'GET_USER_TRAVEL_SUCCESS';
export const GET_USER_TRAVEL_FAILURE = 'GET_USER_TRAVEL_FAILURE';
export const UPDATE_PROFILE__SUCCESS = 'UPDATE_PROFILE__SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const GET_PLACE_SUCCESS = 'GET_PLACE_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
